[package]
name = "spotify_all_songs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spotify-rs = "0.3.10"
tokio = { version = "1.36.0", features = ["full"] }
chrono = "0.4.35"
url = "2.5.0"
